name: CCDS
description: Check and correct directory structure
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r $action_path/requirements.txt
      shell: bash
      env:
        action_path: ${{ github.action_path }}

    - name: Check structure and Generate metadata
      run: python $action_path/check_structure.py
      shell: bash
      env:
        action_path: ${{ github.action_path }}
    
    - name: Fix structure
      run: python $action_path/fix_structure.py
      shell: bash
      env:
        action_path: ${{ github.action_path }}
    
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      shell: bash
    
    - name: Add Files
      run: git add .
      shell: bash
    
    - name: Commit Changes
      run: |
        ppsversion=$(<$action_path/version)
        git commit -m "STRUCTURE UPDATE (pps@v$ppsversion)"
      shell: bash
      env:
        action_path: ${{ github.action_path }}

    - name: Sync
      run: git push
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}