name: python-project-structure
description: Check and correct directory structure for PYPI
inputs:
  GH_API_TOKEN:
    description: "GitHub Personal Access Token"
    required: False
    default: $ {{ github.token }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r $action_path/requirements.txt
      shell: bash
      env:
        action_path: ${{ github.action_path }}

    - name: Check structure and Generate metadata
      run: python $action_path/codes/check_structure.py
      shell: bash
      env:
        action_path: ${{ github.action_path }}
    
    - name: Fix structure
      run: python $action_path/codes/fix_structure.py
      shell: bash
      env:
        action_path: ${{ github.action_path }}
    
    - name: Transfer Dependencies if any.
      run: python $action_path/codes/check_n_fix_requirements.txt.py
      shell: bash
      env:
        action_path: ${{ github.action_path }}
    
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
      shell: bash
    
    - name: Add Files
      run: git add .
      shell: bash
    
    - name: Commit Changes
      run: |
        ppsversion=$(<$action_path/version)
        git commit -m "Structure Update (pps@v$ppsversion)"
      shell: bash
      env:
        action_path: ${{ github.action_path }}

    - name: Sync
      run: |
        git push 
      shell: bash
      env:
        # action_path: ${{ github.action_path }}
        GITHUB_TOKEN: ${{ inputs.GH_API_TOKEN }}
branding:
  icon: box
  color: black