name: CCDS
description: Check and correct directory structure
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    # - name: Set Github Action path
    #   run: |
    #     echo "$GHA_PATH" >> $GITHUB_PATH
    #     echo "$GHA_PATH"
    #   shell: bash
    #   env:
    #     GHA_PATH: ${{ github.action_path }}

    - name: Check structure and Generate metadata
      run: python $AP/check_structure.py
      shell: bash
      env:
        AP: ${{ github.action_path }}